laplace2d_config1:
  cost_time_s:
    kpi_base: 48
    kpi_status: Passed
    kpi_value: None
    ratio: 0
    threshold: 0.05
  mean_square_error:
    kpi_base: 5.3e-05
    kpi_status: Passed
    kpi_value: None
    ratio: 0
    threshold: 0.001
