laplace2d_10000_epoch:
  cost_time_s:
    kpi_base: 75.85153937339783
    kpi_status: Passed
    kpi_value: None
    ratio: 0
    threshold: 0.01
  mean_square_error:
    kpi_base: 0.00268508429481006
    kpi_status: Passed
    kpi_value: None
    ratio: 0
    threshold: 0.0001
laplace2d_2000_epoch:
  cost_time_s:
    kpi_base: 13
    kpi_status: Passed
    kpi_value: None
    ratio: 0
    threshold: 0
  mean_square_error:
    kpi_base: 0.003131445944630601
    kpi_status: Passed
    kpi_value: None
    ratio: 0
    threshold: 0.001
